In [1]:
import os

path = r"C:\Users\vyjay\Downloads\AI-Powered Agricultural Intelligence & Analytics Platform\archive"

print(os.listdir(path))

['.ipynb_checkpoints', 'pesticides.csv', 'rainfall.csv', 'temp.csv', 'Untitled.ipynb', 'yield.csv', 'yield_df.csv']


In [3]:
import pandas as pd

path = r"C:\Users\vyjay\Downloads\AI-Powered Agricultural Intelligence & Analytics Platform\archive\yield_df.csv"

df = pd.read_csv(path)

df.head()

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37


In [4]:
df.shape

(28242, 8)

In [5]:
df.columns

Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Unnamed: 0                     28242 non-null  int64  
 1   Area                           28242 non-null  object 
 2   Item                           28242 non-null  object 
 3   Year                           28242 non-null  int64  
 4   hg/ha_yield                    28242 non-null  int64  
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), object(2)
memory usage: 1.7+ MB


In [7]:

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully


In [8]:

path = r"C:\Users\vyjay\Downloads\AI-Powered Agricultural Intelligence & Analytics Platform\archive\yield_df.csv"

df = pd.read_csv(path)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully


In [9]:
df.tail()

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
28237,28237,Zimbabwe,"Rice, paddy",2013,22581,657.0,2550.07,19.76
28238,28238,Zimbabwe,Sorghum,2013,3066,657.0,2550.07,19.76
28239,28239,Zimbabwe,Soybeans,2013,13142,657.0,2550.07,19.76
28240,28240,Zimbabwe,Sweet potatoes,2013,22222,657.0,2550.07,19.76
28241,28241,Zimbabwe,Wheat,2013,22888,657.0,2550.07,19.76


In [10]:
print("="*60)

print("Dataset Shape")

print("="*60)

print(f"Rows    : {df.shape[0]}")

print(f"Columns : {df.shape[1]}")

Dataset Shape
Rows    : 28242
Columns : 8


In [11]:
print("="*60)

print("Dataset Information")

print("="*60)

df.info()

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Unnamed: 0                     28242 non-null  int64  
 1   Area                           28242 non-null  object 
 2   Item                           28242 non-null  object 
 3   Year                           28242 non-null  int64  
 4   hg/ha_yield                    28242 non-null  int64  
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), object(2)
memory usage: 1.7+ MB


In [12]:
datatype = pd.DataFrame({

    "Column":df.columns,

    "Data Type":df.dtypes

})

datatype

,Column,Data Type
Unnamed: 0,Unnamed: 0,int64
Area,Area,object
Item,Item,object
Year,Year,int64
hg/ha_yield,hg/ha_yield,int64
average_rain_fall_mm_per_year,average_rain_fall_mm_per_year,float64
pesticides_tonnes,pesticides_tonnes,float64
avg_temp,avg_temp,float64


In [13]:
df.rename(columns={

    "hg/ha_yield":"Crop_Yield",

    "average_rain_fall_mm_per_year":"Rainfall",

    "pesticides_tonnes":"Pesticides",

    "avg_temp":"Temperature"

}, inplace=True)

df.head()

,Unnamed: 0,Area,Item,Year,Crop_Yield,Rainfall,Pesticides,Temperature
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37


In [14]:
df.drop(

    columns=["Unnamed: 0"],

    inplace=True

)

df.head()

,Area,Item,Year,Crop_Yield,Rainfall,Pesticides,Temperature
0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37


In [15]:
missing = pd.DataFrame({

    "Missing Values":df.isnull().sum(),

    "Percentage":(

        df.isnull().sum()/len(df)

    )*100

})

missing

,Missing Values,Percentage
Area,0,0.0
Item,0,0.0
Year,0,0.0
Crop_Yield,0,0.0
Rainfall,0,0.0
Pesticides,0,0.0
Temperature,0,0.0


In [16]:
duplicates = df.duplicated().sum()

print("="*60)

print("Duplicate Records")

print("="*60)

print(duplicates)

Duplicate Records
2310


In [17]:
for col in df.columns:

    print("="*60)

    print(col)

    print()

    print("Unique Values :",df[col].nunique())

    print(df[col].unique()[:10])

    print()

Area

Unique Values : 101
['Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain']

Item

Unique Values : 10
['Maize' 'Potatoes' 'Rice, paddy' 'Sorghum' 'Soybeans' 'Wheat' 'Cassava'
 'Sweet potatoes' 'Plantains and others' 'Yams']

Year

Unique Values : 23
[1990 1991 1992 1993 1994 1995 1996 1997 1998 1999]

Crop_Yield

Unique Values : 11514
[36613 66667 23333 12500  7000 30197 29068 77818 28538  6667]

Rainfall

Unique Values : 100
[1485.   89. 1010.  591.  562.  534. 1110.  447. 1292.   83.]

Pesticides

Unique Values : 1673
[121.   201.   251.   313.96 376.93 439.89 502.86 565.82 628.79 691.75]

Temperature

Unique Values : 1831
[16.37 15.36 16.06 16.05 16.96 15.67 15.64 15.9  16.27 16.57]



In [18]:
df.describe()

,Year,Crop_Yield,Rainfall,Pesticides,Temperature
count,28242.000000,28242.000000,28242.00000,28242.000000,28242.000000
mean,2001.544296,77053.332094,1149.05598,37076.909344,20.542627
std,7.051905,84956.612897,709.81215,59958.784665,6.312051
min,1990.000000,50.000000,51.00000,0.040000,1.300000
25%,1995.000000,19919.250000,593.00000,1702.000000,16.702500
50%,2001.000000,38295.000000,1083.00000,17529.440000,21.510000
75%,2008.000000,104676.750000,1668.00000,48687.880000,26.000000
max,2013.000000,501412.000000,3240.00000,367778.000000,30.650000


In [19]:
df.describe(include="object")

,Area,Item
count,28242,28242
unique,101,10
top,India,Potatoes
freq,4048,4276


In [20]:
dictionary = pd.DataFrame({

    "Column":df.columns,

    "Datatype":df.dtypes,

    "Missing":df.isnull().sum(),

    "Unique":df.nunique()

})

dictionary

,Column,Datatype,Missing,Unique
Area,Area,object,0,101
Item,Item,object,0,10
Year,Year,int64,0,23
Crop_Yield,Crop_Yield,int64,0,11514
Rainfall,Rainfall,float64,0,100
Pesticides,Pesticides,float64,0,1673
Temperature,Temperature,float64,0,1831


In [21]:
dictionary.to_csv(

    "data_dictionary.csv",

    index=False

)

print("Data Dictionary Exported Successfully")

Data Dictionary Exported Successfully


In [22]:
print("="*70)

print("DATA VALIDATION REPORT")

print("="*70)

print()

print(f"Total Rows            : {len(df)}")

print(f"Total Columns         : {len(df.columns)}")

print(f"Missing Values        : {df.isnull().sum().sum()}")

print(f"Duplicate Records     : {df.duplicated().sum()}")

print()

print("Dataset Ready for Cleaning")

DATA VALIDATION REPORT

Total Rows            : 28242
Total Columns         : 7
Missing Values        : 0
Duplicate Records     : 2310

Dataset Ready for Cleaning


In [23]:
df.to_csv(

    "validated_crop_data.csv",

    index=False

)

print("Validated Dataset Saved Successfully")

Validated Dataset Saved Successfully
